name: build
on: 
  workflow_dispatch:
    inputs:
      matrix: 
        type: string
        default: '{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}'

jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}
    steps:
      - run: echo "hi"